# Generated by Django 3.0.7 on 2020-06-12 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('A', 'Apple'), ('H', 'HP'), ('M', 'Microsoft'), ('S', 'Sony')], max_length=1)),
                ('type', models.CharField(choices=[('D', 'Desktop'), ('L', 'Laptop'), ('N', 'Netbook')], max_length=1)),
                ('operating_system', models.CharField(choices=[('L', 'Linux'), ('M', 'MacOS'), ('W', 'Windows')], max_length=1)),
                ('memory', models.IntegerField()),
                ('serial_number', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_created_by', related_query_name='computer_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
                'ordering': ['type', 'brand'],
            },
        ),
    ]
