# Generated by Django 3.1.3 on 2020-11-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computers', '0002_auto_20201106_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='user',
            new_name='myuser',
        ),
    ]
