# Generated by Django 3.2.4 on 2021-06-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computers', '0003_auto_20201127_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
