# Generated by Django 3.1.4 on 2020-12-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computers', '0003_auto_20201127_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
    ]
