# Generated by Django 3.1.3 on 2020-11-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='some_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
