# Generated by Django 3.2.9 on 2021-11-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='some_file',
        ),
    ]
