# Generated by Django 3.2.9 on 2021-11-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
