# Generated by Django 3.2.9 on 2021-12-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_game_average_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='myuser',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='myuser',
        ),
    ]
