# Generated by Django 3.2.9 on 2021-12-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0005_auto_20211203_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user',
            new_name='myuser',
        ),
    ]
