# Generated by Django 3.2.9 on 2021-11-21 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Games', '0010_alter_vote_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
