# Generated by Django 3.2.9 on 2021-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0012_alter_vote_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ManyToManyField(null=True, to='Games.Comment'),
        ),
    ]
