# Generated by Django 3.2.9 on 2021-11-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0013_auto_20211121_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.ManyToManyField(to='Games.Comment'),
        ),
    ]
