# Generated by Django 3.1.4 on 2021-01-15 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0004_myuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2001, 1, 15)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='type',
            field=models.CharField(choices=[('SU', 'superuser'), ('CS', 'customer service'), ('CU', 'customer'), ('BP', 'business partner')], default='CU', max_length=2),
        ),
    ]
